### ISSUE TITLE
When not configured it should not error when cannot emit events

### ISSUE THREAD

**Issue by evilmarty** [everydayhero/nark#5]
When given no configuration it should be silent instead of raising a connection error. If however configuration has been supplied then it should raise an error, or at the very least report them to a log.

**Comment by coop** [comment]
I actually thought we were going to take a UDP cannon approach so it shouldn't matter.

**Comment by evilmarty** [comment]
I meant in the application. Currently my app crashes because I haven't specified the environment variables.

**Comment by coop** [comment]
Damn. Gonna miss this issue.

**Comment by evilmarty** [comment]
It's going to miss you too
